spring:
  application:
    name: spring-starter
  datasource:
    url: jdbc:postgresql://localhost:5432/robot
    username: postgres
    password: Coutinho2603
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8300
  servlet:
    context-path: /api/robot
